config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games, only: [:index, :show]
  resource :users, only: [:show]
  # resources :users, only: [:index, :show]

  get "/auth/twitch", as: :twitch_login
  get "/auth/twitch/callback", to: "sessions#create"
  # get "/auth/:provider/callback", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "logout"

  get '/user/dashboard', to: 'users#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    # binding.pry
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.display_name       = auth_info.extra.raw_info.display_name
      new_user.email              = auth_info.extra.raw_info.email
      new_user.bio                = auth_info.extra.raw_info.bio
      new_user.links              = auth_info.extra.raw_info._links.self
      new_user.logo               = auth_info.extra.raw_info.logo
      new_user.push_notifs        = auth_info.extra.raw_info.notifications.push
      new_user.email_notifs       = auth_info.extra.raw_info.notifications.email
      new_user.partnered          = auth_info.extra.raw_info.partnered
      new_user.user_type          = auth_info.extra.raw_info.type
      new_user.nickname           = auth_info.info.nickname
      new_user.image              = auth_info.info.image
      new_user.twitch_url         = auth_info.info.urls["Twitch"]
      new_user.provider           = auth_info.provider
      new_user.oauth_token        = auth_info.credentials.token
    end
  end

  # def self.find_by(params)
  #   service = TwitchService.new
  #   service.users(params).map {|raw_info| User.new(raw_info)}
  # end

  def followed_streams
    service = TwitchService.new
    TwitchService.new.followed_by_user(self)
  end

  # def followed_streams
  #   TwitchService.new.followed_by_user(self)
  # end

#   class Legislator < OpenStruct
#   def self.find_by(params)
#     service = SunlightService.new
#     service.legislators(params).map {|raw_leg|
#       Legislator.new(raw_leg)
#     }
#   end
# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    # binding.pry
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    # @games = Game.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def create
  #   binding.pry
  #   render text: request.env["omniauth.auth"].inspect
  # end

  def create
  if user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
  end
  flash[:now] = "You've logged in!"
  redirect_to root_path
end

  def destroy
    session.clear
    flash[:now] = "You've logged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/games/index.html.erb
<div class="well col-md-10">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCuriousTwitch</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
  <div class="flash-messages">
    <% flash.each do |name, msg| %>
      <div class= "alert alert-<%= "#{name}" %> btn-font-size" role: "alert">
        <%= sanitize(msg) %>
      </div>
    <% end %>
  </div>
  <%= render partial: "shared/main_navbar" %>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_main_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand big-big-font" href="<%= root_path %>">TWITCH</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %>
          <span class="glyphicon glyphicon-log-out"></span></li>
          <li><a href="<%= "#" %>" class="cart-link">
          <span class="glyphicon glyphicon-user"></span><%= current_user.name.capitalize %>'s Account</a></li>
        <% else %>
          <li><%= link_to "Login with Twitch", twitch_login_path %>
          <span class="glyphicon glyphicon-log-in"></span></a></li>
          <li><a href="<%= "#" %>" class="cart-link">
          <span class="glyphicon glyphicon-user"></span>Create Account</a></li>
          <li><a href="<%= "#" %>" class="category-link">Categories</a></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<%= @user.display_name.capitalize %>
<br>
<%= @user.followed_streams %>